### ISSUE TITLE
Is this repo still active/alive?

### ISSUE THREAD

**Issue by tnrich** [Glavin001/graphql-sequelize-crud#27]
So, is anyone still maintaining this repo? It is a really cool project so I hope it can be maintained.

In the meantime, we at Teselagen have forked this repo,  customized it to our needs, and have published it to npm as `graphql-sequelize-crud-teselagen`. We've added some new features like counts, batch updates (multiple where queries) and nested creates.

**Comment by Glavin001** [comment]
Hi! Sorry @tnrich , I have not been using this lately for my projects (work and otherwise), however I would love for some support to maintain it.

If you are interested, I could add you as a contributor and we could review and merge in the changes from `graphql-sequelize-crud-teselagen` and grow support for this project. I am still getting back into maintaining my open-source projects, as I just recently finished my University degree and now should have a little more time 😃 .
Thank you for your interest in the project!

**Comment by tnrich** [comment]
Hi @Glavin001 , good to hear you're still alive and kicking :) 

I think that would be awesome to become a contributor to the repo. 

We'll still be maintaining our fork of your code but hopefully any generally useful additions we make can be merged back into this repo.

**Comment by Glavin001** [comment]
Excellent! I have added you as a contributor now. Looking forward to getting these repositories merged back together for the community's benefit. Thanks!

**Comment by Glavin001** [comment]
I have an upcoming project which I plan on using this library for. Hopefully more improvements coming along soon 😄 .

**Comment by Glavin001** [comment]
Here's a diff between our two repositories: https://github.com/Glavin001/graphql-sequelize-crud/compare/v0.3.0...TeselaGen:master

**Comment by Glavin001** [comment]
Published a big new release, v0.4.1! https://github.com/Glavin001/graphql-sequelize-crud/releases/tag/v0.4.1
